app_debug: false

# 监听ip
server_ip: 127.0.0.1

ports: # 监听端口
    - 8080
    - 8081
    - 9000
    - 9001

# 日志
log:
    level: debug # 日志等级 trace debug info warn error fatal panic

# redis 配置
redis:
    host: 127.0.0.1
    port: 6379
    password:
    db: 1

# mysql 配置
mysql:
    hostname: 127.0.0.1
    database: kuyo_logic_server_acc
    username: root
    password: root
    port: 3306

smtp:
    username: xxx@aliyun.com
    password: password
    host: smtpdm.aliyun.com
    port: 465,
    tls: true